# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Pranav@02
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# Server Configuration
server:
  port: 8080

# Additional Configuration
# Add any additional configuration properties here as needed
